package com.hongocman.quanlymonhoc.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BUOI_HOC_MODEL".
 */
public class BuoiHocModel {

    /** Not-null value. */
    private String ID;
    private String Description;
    private Integer StartTime;
    private Integer EndTime;

    public BuoiHocModel() {
    }

    public BuoiHocModel(String ID) {
        this.ID = ID;
    }

    public BuoiHocModel(String ID, String Description, Integer StartTime, Integer EndTime) {
        this.ID = ID;
        this.Description = Description;
        this.StartTime = StartTime;
        this.EndTime = EndTime;
    }

    /** Not-null value. */
    public String getID() {
        return ID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setID(String ID) {
        this.ID = ID;
    }

    public String getDescription() {
        return Description;
    }

    public void setDescription(String Description) {
        this.Description = Description;
    }

    public Integer getStartTime() {
        return StartTime;
    }

    public void setStartTime(Integer StartTime) {
        this.StartTime = StartTime;
    }

    public Integer getEndTime() {
        return EndTime;
    }

    public void setEndTime(Integer EndTime) {
        this.EndTime = EndTime;
    }

}
