package com.hongocman.quanlymonhoc.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DANG_KY_BUOI_HOC_MODEL".
 */
public class DangKyBuoiHocModel {

    private String MonHocID;
    private String SinhVienID;
    private java.util.Date Date;

    public DangKyBuoiHocModel() {
    }

    public DangKyBuoiHocModel(String MonHocID, String SinhVienID, java.util.Date Date) {
        this.MonHocID = MonHocID;
        this.SinhVienID = SinhVienID;
        this.Date = Date;
    }

    public String getMonHocID() {
        return MonHocID;
    }

    public void setMonHocID(String MonHocID) {
        this.MonHocID = MonHocID;
    }

    public String getSinhVienID() {
        return SinhVienID;
    }

    public void setSinhVienID(String SinhVienID) {
        this.SinhVienID = SinhVienID;
    }

    public java.util.Date getDate() {
        return Date;
    }

    public void setDate(java.util.Date Date) {
        this.Date = Date;
    }

}
