package com.hongocman.quanlymonhoc.models;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.hongocman.quanlymonhoc.models.SinhVienModelDao;
import com.hongocman.quanlymonhoc.models.GiangVienModelDao;
import com.hongocman.quanlymonhoc.models.MonHocModelDao;
import com.hongocman.quanlymonhoc.models.DangKyMonHocModelDao;
import com.hongocman.quanlymonhoc.models.BuoiHocModelDao;
import com.hongocman.quanlymonhoc.models.ThuModelDao;
import com.hongocman.quanlymonhoc.models.ThoiKhoaBieuModelDao;
import com.hongocman.quanlymonhoc.models.DiemDanhModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1000): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1000;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        SinhVienModelDao.createTable(db, ifNotExists);
        GiangVienModelDao.createTable(db, ifNotExists);
        MonHocModelDao.createTable(db, ifNotExists);
        DangKyMonHocModelDao.createTable(db, ifNotExists);
        BuoiHocModelDao.createTable(db, ifNotExists);
        ThuModelDao.createTable(db, ifNotExists);
        ThoiKhoaBieuModelDao.createTable(db, ifNotExists);
        DiemDanhModelDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        SinhVienModelDao.dropTable(db, ifExists);
        GiangVienModelDao.dropTable(db, ifExists);
        MonHocModelDao.dropTable(db, ifExists);
        DangKyMonHocModelDao.dropTable(db, ifExists);
        BuoiHocModelDao.dropTable(db, ifExists);
        ThuModelDao.dropTable(db, ifExists);
        ThoiKhoaBieuModelDao.dropTable(db, ifExists);
        DiemDanhModelDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(SinhVienModelDao.class);
        registerDaoClass(GiangVienModelDao.class);
        registerDaoClass(MonHocModelDao.class);
        registerDaoClass(DangKyMonHocModelDao.class);
        registerDaoClass(BuoiHocModelDao.class);
        registerDaoClass(ThuModelDao.class);
        registerDaoClass(ThoiKhoaBieuModelDao.class);
        registerDaoClass(DiemDanhModelDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
