package com.hongocman.quanlymonhoc.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DIEM_DANH_MODEL".
 */
public class DiemDanhModel {

    private Long ID;
    private String MonHocID;
    private String SinhVienID;
    private String BuoiID;
    private String ThuID;
    private Boolean Status;
    private java.util.Date Date;

    public DiemDanhModel() {
    }

    public DiemDanhModel(Long ID) {
        this.ID = ID;
    }

    public DiemDanhModel(Long ID, String MonHocID, String SinhVienID, String BuoiID, String ThuID, Boolean Status, java.util.Date Date) {
        this.ID = ID;
        this.MonHocID = MonHocID;
        this.SinhVienID = SinhVienID;
        this.BuoiID = BuoiID;
        this.ThuID = ThuID;
        this.Status = Status;
        this.Date = Date;
    }

    public Long getID() {
        return ID;
    }

    public void setID(Long ID) {
        this.ID = ID;
    }

    public String getMonHocID() {
        return MonHocID;
    }

    public void setMonHocID(String MonHocID) {
        this.MonHocID = MonHocID;
    }

    public String getSinhVienID() {
        return SinhVienID;
    }

    public void setSinhVienID(String SinhVienID) {
        this.SinhVienID = SinhVienID;
    }

    public String getBuoiID() {
        return BuoiID;
    }

    public void setBuoiID(String BuoiID) {
        this.BuoiID = BuoiID;
    }

    public String getThuID() {
        return ThuID;
    }

    public void setThuID(String ThuID) {
        this.ThuID = ThuID;
    }

    public Boolean getStatus() {
        return Status;
    }

    public void setStatus(Boolean Status) {
        this.Status = Status;
    }

    public java.util.Date getDate() {
        return Date;
    }

    public void setDate(java.util.Date Date) {
        this.Date = Date;
    }

}
