package com.hongocman.quanlymonhoc.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MON_HOC_MODEL".
 */
public class MonHocModel {

    private String ID;
    private String Description;
    private java.util.Date FromDate;
    private java.util.Date ToDate;

    public MonHocModel() {
    }

    public MonHocModel(String ID, String Description, java.util.Date FromDate, java.util.Date ToDate) {
        this.ID = ID;
        this.Description = Description;
        this.FromDate = FromDate;
        this.ToDate = ToDate;
    }

    public String getID() {
        return ID;
    }

    public void setID(String ID) {
        this.ID = ID;
    }

    public String getDescription() {
        return Description;
    }

    public void setDescription(String Description) {
        this.Description = Description;
    }

    public java.util.Date getFromDate() {
        return FromDate;
    }

    public void setFromDate(java.util.Date FromDate) {
        this.FromDate = FromDate;
    }

    public java.util.Date getToDate() {
        return ToDate;
    }

    public void setToDate(java.util.Date ToDate) {
        this.ToDate = ToDate;
    }

}
