package com.hongocman.quanlymonhoc.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SINH_VIEN_MODEL".
 */
public class SinhVienModel {

    /** Not-null value. */
    private String ID;
    private String FullName;
    private Boolean Sex;
    private String Password;
    private String Passport;
    private String PhoneNumber;
    private java.util.Date BirthDay;

    private boolean diemDanhStatus = false;

    public SinhVienModel() {
    }

    public SinhVienModel(String ID) {
        this.ID = ID;
    }

    public SinhVienModel(String ID, String FullName, Boolean Sex, String Password, String Passport, String PhoneNumber, java.util.Date BirthDay) {
        this.ID = ID;
        this.FullName = FullName;
        this.Sex = Sex;
        this.Password = Password;
        this.Passport = Passport;
        this.PhoneNumber = PhoneNumber;
        this.BirthDay = BirthDay;
    }

    /** Not-null value. */
    public String getID() {
        return ID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setID(String ID) {
        this.ID = ID;
    }

    public String getFullName() {
        return FullName;
    }

    public void setFullName(String FullName) {
        this.FullName = FullName;
    }

    public Boolean getSex() {
        return Sex;
    }

    public void setSex(Boolean Sex) {
        this.Sex = Sex;
    }

    public String getPassword() {
        return Password;
    }

    public void setPassword(String Password) {
        this.Password = Password;
    }

    public String getPassport() {
        return Passport;
    }

    public void setPassport(String Passport) {
        this.Passport = Passport;
    }

    public String getPhoneNumber() {
        return PhoneNumber;
    }

    public void setPhoneNumber(String PhoneNumber) {
        this.PhoneNumber = PhoneNumber;
    }

    public java.util.Date getBirthDay() {
        return BirthDay;
    }

    public void setBirthDay(java.util.Date BirthDay) {
        this.BirthDay = BirthDay;
    }

    public  void setDiemDanhStatus(boolean status){
        this.diemDanhStatus = status;
    }

    public  boolean getDiemDanhStatus(){
        return  diemDanhStatus;
    }
}
