package com.hongocman.quanlymonhoc.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "THOI_KHOA_BIEU_MODEL".
 */
public class ThoiKhoaBieuModel {

    /** Not-null value. */
    private String BuoiID;
    /** Not-null value. */
    private String MonHocID;
    /** Not-null value. */
    private String ThuID;

    public ThoiKhoaBieuModel() {
    }

    public ThoiKhoaBieuModel(String BuoiID, String MonHocID, String ThuID) {
        this.BuoiID = BuoiID;
        this.MonHocID = MonHocID;
        this.ThuID = ThuID;
    }

    /** Not-null value. */
    public String getBuoiID() {
        return BuoiID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBuoiID(String BuoiID) {
        this.BuoiID = BuoiID;
    }

    /** Not-null value. */
    public String getMonHocID() {
        return MonHocID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMonHocID(String MonHocID) {
        this.MonHocID = MonHocID;
    }

    /** Not-null value. */
    public String getThuID() {
        return ThuID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setThuID(String ThuID) {
        this.ThuID = ThuID;
    }

}
